services:
  db:
    image: postgres:15-alpine
    container_name: database
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: text-to-sql-db
    ports:
      - "5432:5432"
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
